default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: localhost

development:
  <<: *default
  database: final_capstone_dev

test:
  <<: *default
  database: final_capstone_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>